name: Build Debug

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Debug

jobs:
  dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: build GameLiftServerSDK
        run: |
          curl -Lo sandbox/GameLift-CSharp-ServerSDK.zip https://gamelift-server-sdk-release.s3.us-west-2.amazonaws.com/csharp/GameLift-CSharp-ServerSDK-5.1.2.zip
          unzip -o sandbox/GameLift-CSharp-ServerSDK.zip -d sandbox/GameLift-CSharp-ServerSDK
          dotnet build -f net6.0 -c Debug sandbox/GameLift-CSharp-ServerSDK/src/GameLiftServerSDK.sln
          cp sandbox/GameLift-CSharp-ServerSDK/src/src/GameLiftServerSDK/bin/x64/Debug/net6.0/GameLiftServerSDK.dll sandbox/GameLiftMagicOnionServer/lib/.
      - name: dotnet build
        run: dotnet build -c "${{ env.BUILD_CONFIG }}"
      - name: dotnet test
        run: dotnet test -c "${{ env.BUILD_CONFIG }}" --logger GitHubActions --logger "console;verbosity=normal"
      - name: docker build
        run: docker compose build
